atlantis_base_simulator:
  ros__parameters:
    use_sim_time: True
    goal_tolerance: 2.0
    scenario: "mine"
    map: "mine_small_reverse.yaml"
    lattice_primitives: "volvo_l70_cardinality3"
    primitives_dir: "src/ecceleron_ros2/navigation/ecceleron_global_planner/lattice_primitives/Volvo_L70/"
    robots: ["robot1", "robot2"]
    materials: ["mat1", "mat2"]
    waypoints_file: "mine2_waypoints.txt"
    #waypoints: ["wp1" , "wp2" ,"wp3", "wp4"]
    metrics: ["computational_time" , "path_length", ]
    use_trajectory_dt: true
    dt: 0.1
    real_time_factor: 2.
    robot1:
      ID: 1
      type: 2
      #model: "package://turtlebot3_description/meshes/bases/burger_base.stl"
      footprint: "[[1.0, -1.0], [1.0, 1.0], [-1.0, 1.0], [-1.0, -1.0]]"
      planner: "Hybrid"
      initial_pose:
        x: 10.0
        y: 10.0
        z: 0.0
        yaw: 0.0
    robot2:
      ID: 2
      type: 2
      #model: "package://turtlebot3_description/meshes/bases/burger_base.stl"
      footprint: "[[1.0, -1.0], [1.0, 1.0], [-1.0, 1.0], [-1.0, -1.0]]"
      planner: "Hybrid"
      initial_pose:
        x: 20.0
        y: 20.0
        z: 0.0
        yaw: 0.0
    mat1:
      locations: ["wp1", "wp3"]
      wp1:
        amount: 10.0
      wp3:
        amount: 10.0
    mat2:
      locations: ["wp2"]
      wp2:
        amount: 10.0

ecl_fleet_coordination:
  ros__parameters:
    use_sim_time: True
    params:
      origin:
        x: -1.
        y: -1.
      resolution: 0.1
      width: 400
      height: 400
    robots: ["robot1", "robot2"]
    robot1:
      ID: 1
      type: 2
    robot2:
      ID: 2
      type: 2

atlantis_simple_commander:
   ros__parameters:
    use_sim_time: True
    robot_ids: [1,2]
    actions: ["MoveTo", "Load", "Dump"]

ecceleron_simple_commander:
   ros__parameters:
    use_sim_time: True
    robot_ids: [1,2]
    actions: ["MoveTo", "Load", "Dump"]


