atlantis_discrete_event_simulator:
  ros__parameters:
    use_sim_time: True
    execution_sec: 2
    waypoints: ["load1" , "dump1" ,"home1"]

    waypoint_publisher:
      topic: "waypoints"
      frame_id: "map"

    metrics: ["computational_time" , "path_length"]
    load1:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0.0
    dump1:
      x: 1.0
      y: 0.0
      z: 0.0
      yaw: 0.0
    home1:
      x: 2.0
      y: 0.0
      z: 0.0
      yaw: 0.0
    robots: ["robot1"]
    robot1:
      type: "vehicle"
      capacity: 12.0
    materials: ["mat1"]
    mat1:
      locations: ["load1"]
      load1:
        amount: 10.0

    # ---- Action plugins (applied to every robot) ----
    actions: ["move", "load", "dump"]

    move:
      type: "atlantis_simulator::MoveActionPlugin"
      topic: "move_to_pose"
    load:
      type: "atlantis_simulator::LoadActionPlugin"
      topic: "send_load"
    dump:
      type: "atlantis_simulator::DumpActionPlugin"
      topic: "send_dump"

    # ---- Service plugins (applied to every robot) ----
    services: ["get_material_amount"]

    get_material_amount:
      type: "atlantis_simulator::MaterialAmountServicePlugin"
      topic: "get_material_amount"

atlantis_base_simulator:
  ros__parameters:
    use_sim_time: True
    goal_tolerance: 2.0
    map: "package://atlantis_collection/scenarios/construction/map2.yaml"
    waypoints_file: "package://atlantis_collection/scenarios/construction/map1_waypoints.txt"
    #waypoints: ["wp1" , "wp2" ,"wp3", "wp4"]
    #wp1:
     # x: 40.01
     # y: 116.76
     # z: 0.0
     # yaw: 2.59
    robots: ["robot1", "robot2"]
    max_planning_time: 3.0
    randomness: True
    uncertainty: 0.30
    use_precomputed_paths: True
    precomputed_paths_folder: "package://atlantis_collection/scenarios/construction/paths"
    #max_sim_time: 5.0
    materials: ["mat1", "mat2", "mat3"]
    metrics: ["computational_time" , "path_length"]
    refilling: false
    use_trajectory_dt: true
    dt: 0.1
    real_time_factor: 10.
    robot1:
      ID: 1
      type: "truck"
      capacity: 10.0
      minimum_turning_radius: 8.0
      model: "package://atlantis_collection/models/mine_truck.stl"
      footprint: "[[1.0, -1.0], [1.0, 1.0], [-1.0, 1.0], [-1.0, -1.0]]"
      planner: "Hybrid"
      initial_pose:
        x: 62.2773
        y: 10.3697
        z: 0.0
        yaw: -0.847167
    robot2:
      ID: 2
      type: "truck"
      capacity: 10.0
      minimum_turning_radius: 8.0
      model: "package://atlantis_collection/models/mine_truck.stl"
      footprint: "[[1.0, -1.0], [1.0, 1.0], [-1.0, 1.0], [-1.0, -1.0]]"
      planner: "Hybrid"
      initial_pose:
        x: 93.8028
        y: 8.59434
        z: 0.0
        yaw: -0.847167
    mat1:
      locations: ["load5"]
      load5:
        amount: 50.0
    mat2:
      locations: ["load3"]
      load3:
        amount: 50.0
    mat3:
      locations: ["load10"]
      load10:
        amount: 50.0

    actions: ["move", "load", "dump"]

    move:
      type: "atlantis_base::MoveActionPlugin"
      topic: "navigate_to_pose"
    load:
      type: "atlantis_base::LoadActionPlugin"
      topic: "send_load"
    dump:
      type: "atlantis_base::DumpActionPlugin"
      topic: "send_dump"

    # ---- Service plugins (applied to every robot) ----
    services: ["get_material_amount", "get_waypoint_list"]

    get_material_amount:
      type: "atlantis_base::MaterialAmountServicePlugin"
      topic: "get_material_amount"
    get_waypoint_list:
      type: "atlantis_base::WaypointListServicePlugin"
      topic: "get_waypoint_list"


atlantis_simple_commander:
   ros__parameters:
    use_sim_time: True
    waypoints_file: "package://atlantis_collection/scenarios/construction/map1_waypoints.txt"
    robots: ["robot1", "robot2"]
    actions: ["MoveTo", "Load", "Dump"]

state_generator:
  ros__parameters:
    state_generator_plugin: "PDDL"
    robots: ["robot1", "robot2"]
    PDDL:
      plugin: "atlantis_state::PddlStateGenerator"
